# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sigflare < Formula
  desc "Supply chain risk assessment at install-time"
  homepage "https://sigflare.dev"
  version "0.1.0"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lwstudios-bp/sigflare/releases/download/v0.1.0/sigflare_0.1.0_darwin_amd64.tar.gz"
      sha256 "13928c88fe7f89ad9df2e9d7b6c78fbf5c6eee87aec52d4f76a5bac3028535b6"

      define_method(:install) do
        bin.install "sigflare"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lwstudios-bp/sigflare/releases/download/v0.1.0/sigflare_0.1.0_darwin_arm64.tar.gz"
      sha256 "af36d57026eb7e6095d77a47aa34bb52f2d06297ee6b23f7eb866b5eae9ab1d6"

      define_method(:install) do
        bin.install "sigflare"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lwstudios-bp/sigflare/releases/download/v0.1.0/sigflare_0.1.0_linux_amd64.tar.gz"
      sha256 "7c70b9292235969c731cee6b5c83d830cfb3d1edfb067ae17f94b6dcc56ec76c"
      define_method(:install) do
        bin.install "sigflare"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lwstudios-bp/sigflare/releases/download/v0.1.0/sigflare_0.1.0_linux_arm64.tar.gz"
      sha256 "61e0c40b08c2c811fc758ad374de08ba3d8578609782578ae088a229c0e38145"
      define_method(:install) do
        bin.install "sigflare"
      end
    end
  end

  test do
    system "#{bin}/sigflare", "version"
  end
end
