# This file was generated by GoReleaser. DO NOT EDIT.
cask "sigflare" do
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/lwstudios-bp/sigflare/releases/download/v#{version}/sigflare_#{version}_darwin_amd64.tar.gz"
      sha256 "5d62ab28b4a8a470970941c4699f40d8374e476732d0e9c18edfed1fac7dfd39"
    end
    on_arm do
      url "https://github.com/lwstudios-bp/sigflare/releases/download/v#{version}/sigflare_#{version}_darwin_arm64.tar.gz"
      sha256 "15b45a4735d1ba6da9a845fe1427708d0a834f897a9dd07d9179deca6892acc0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/lwstudios-bp/sigflare/releases/download/v#{version}/sigflare_#{version}_linux_amd64.tar.gz"
      sha256 "0913174d77f0fa090cef42047b798b5b5a2db7e1b913940578f4e4bf8f0373b0"
    end
    on_arm do
      url "https://github.com/lwstudios-bp/sigflare/releases/download/v#{version}/sigflare_#{version}_linux_arm64.tar.gz"
      sha256 "a3e5fc5e5173cc6753af9d643bd70855a88e580786a804656ad522027af89665"
    end
  end

  name "sigflare"
  desc "Supply chain risk assessment at install-time"
  homepage "https://sigflare.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sigflare"

  # No zap stanza required

end
