# This file was generated by GoReleaser. DO NOT EDIT.
cask "sigflare" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "7d6b551f5b30b1b1037d1388c94d46fe007857d0a6e2eb9750630d22af107159"
      url "https://github.com/lwstudios-bp/sigflare/releases/download/v#{version}/sigflare_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "17dd45884866c6df11d1066dadc3bca705ee099aa169f17c509618fe69764d96"
      url "https://github.com/lwstudios-bp/sigflare/releases/download/v#{version}/sigflare_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "623c22285e658903a9611dc280c57e023318612cff3804fc02a94f9c28c2446c"
      url "https://github.com/lwstudios-bp/sigflare/releases/download/v#{version}/sigflare_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c76cb1b4df504c5cdff10e9ca802126d5084ad453526184b0bb8b3230be9eea1"
      url "https://github.com/lwstudios-bp/sigflare/releases/download/v#{version}/sigflare_#{version}_linux_arm64.tar.gz"
    end
  end

  name "sigflare"
  desc "Supply chain risk assessment at install-time"
  homepage "https://sigflare.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sigflare"

  # No zap stanza required

end
