# This file was generated by GoReleaser. DO NOT EDIT.
cask "sigflare" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "05222bb2f3f79799f56820fd331db17956742b1a6f5a4e0a70e155685cc8ce45"
      url "https://github.com/lwstudios-bp/sigflare/releases/download/v#{version}/sigflare_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b3294d7b396b3996206b80e140ab5bfc8c95df1a996335a233d0b52ecaa26b2f"
      url "https://github.com/lwstudios-bp/sigflare/releases/download/v#{version}/sigflare_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "127e862888f10acba5cfa321868695ab83b7ba9389ff852aeab4e68c5b40980a"
      url "https://github.com/lwstudios-bp/sigflare/releases/download/v#{version}/sigflare_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "492c70bcae632c78ac43b03df693f56b639d8efa54049bfcbbb1fa57519f2341"
      url "https://github.com/lwstudios-bp/sigflare/releases/download/v#{version}/sigflare_#{version}_linux_arm64.tar.gz"
    end
  end

  name "sigflare"
  desc "Supply chain risk assessment at install-time"
  homepage "https://sigflare.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sigflare"

  # No zap stanza required

end
